<?xml version="1.0"?>
  <!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED>

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName, Res, DVer?, TSet?, TInst?, RunType?, DT?, Step*, Action+, DIter*, Action*, Summary?, NodeArgs?)> 
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,NodeArgs) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
> <Report ver="2.0" tmZone="中国标准时间">
<General productName="Vugen" productVer="11" os="" host="Y4C9DEK9U2HSHWY"><DocLocation><![CDATA[D:\PerformanceData\OwnerSearch]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[OwnerSearch]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[vuser_init]]></AName>
<Summary sTime="2018/12/12 星期三 - 18:02:00" eTime="2018/12/12 星期三 - 18:02:00" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[vuser_init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[OwnerSearch]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Custom Request: owner]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2018/12/12 星期三 - 18:02:01]]></Time>
<NodeArgs eType="General" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[Custom Request: owner]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration1\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="2018/12/12 星期三 - 18:02:00" eTime="2018/12/12 星期三 - 18:02:01" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" status="Passed" >
<Disp><![CDATA[OwnerSearch Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[OwnerSearch Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T6" iterID="2" >
<Action rID="T7">
<AName><![CDATA[OwnerSearch]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Custom Request: owner]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2018/12/12 星期三 - 18:02:01]]></Time>
<NodeArgs eType="General" icon="4" nRep="14" status="Passed" >
<Disp><![CDATA[Custom Request: owner]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration2\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="2018/12/12 星期三 - 18:02:01" eTime="2018/12/12 星期三 - 18:02:01" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="13" status="Passed" >
<Disp><![CDATA[OwnerSearch Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="12" status="Passed" >
<Disp><![CDATA[OwnerSearch Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T9" iterID="3" >
<Action rID="T10">
<AName><![CDATA[OwnerSearch]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Custom Request: owner]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2018/12/12 星期三 - 18:02:01]]></Time>
<NodeArgs eType="General" icon="4" nRep="19" status="Passed" >
<Disp><![CDATA[Custom Request: owner]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration3\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="2018/12/12 星期三 - 18:02:01" eTime="2018/12/12 星期三 - 18:02:01" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="18" status="Passed" >
<Disp><![CDATA[OwnerSearch Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="17" status="Passed" >
<Disp><![CDATA[OwnerSearch Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T12" iterID="4" >
<Action rID="T13">
<AName><![CDATA[OwnerSearch]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Custom Request: owner]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2018/12/12 星期三 - 18:02:01]]></Time>
<NodeArgs eType="General" icon="4" nRep="24" status="Passed" >
<Disp><![CDATA[Custom Request: owner]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration4\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="2018/12/12 星期三 - 18:02:01" eTime="2018/12/12 星期三 - 18:02:01" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="23" status="Passed" >
<Disp><![CDATA[OwnerSearch Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="22" status="Passed" >
<Disp><![CDATA[OwnerSearch Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T15" iterID="5" >
<Action rID="T16">
<AName><![CDATA[OwnerSearch]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Custom Request: owner]]></Obj>
<Details plainTxt="False" ><![CDATA[<CENTER><STRONG><FONT COLOR=#009A63>Step completed successfully</FONT></STRONG></CENTER>]]></Details>
<Time><![CDATA[2018/12/12 星期三 - 18:02:02]]></Time>
<NodeArgs eType="General" icon="4" nRep="29" status="Passed" >
<Disp><![CDATA[Custom Request: owner]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[\Iteration5\t1.inf]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="2018/12/12 星期三 - 18:02:01" eTime="2018/12/12 星期三 - 18:02:02" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="28" status="Passed" >
<Disp><![CDATA[OwnerSearch Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="27" status="Passed" >
<Disp><![CDATA[OwnerSearch Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<Action rID="T18">
<AName><![CDATA[vuser_end]]></AName>
<Summary sTime="2018/12/12 星期三 - 18:02:02" eTime="2018/12/12 星期三 - 18:02:02" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="32" >
<Disp><![CDATA[vuser_end Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="2018/12/12 星期三 - 18:02:00" eTime="2018/12/12 星期三 - 18:02:02" passed="5" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="4" status="Passed" >
<Disp><![CDATA[Test OwnerSearch Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>